FROM node:lts as build-step
WORKDIR /usr/src/app
COPY /frontend/package*.json /usr/src/app/
RUN npm install
COPY /frontend /usr/src/app/
RUN npm run build --prod

FROM nginx:1.20.1
COPY --from=build-step /usr/src/app/dist/frontend /usr/share/nginx/html
EXPOSE 4200:80