FROM node:lts
WORKDIR /usr/src/app
COPY /frontend/package*.json /usr/src/app/
RUN npm install
COPY /frontend /usr/src/app/
CMD /usr/src/app/node_modules/.bin/ng serve --host 0.0.0.0 --disableHostCheck
