services:
  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./api:/usr/src/app"
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - "./frontend:/usr/src/app"
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #- my-db:/var/lib/mysql
      - "./db/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./db/scripts/seeder.sql:/docker-entrypoint-initdb.d/2.sql"
    ports:
      - "3307:3306"
volumes:
  my-db:
